/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Cliente;
import Entidades.Usuario;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import sistema.Configuracion;
import sistema.SerializadoraGen;

/**
 *
 * @author USUARIO
 */
public class FrameCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrameCliente
     */
    
    Cliente c;
    public FrameCliente() {
        initComponents();
        this.btnModificar.setEnabled(false);
    }
    
    public FrameCliente(Cliente c){
        initComponents();
        this.c=c;
       
        this.inicializarCampos();
        this.btnAgregar.setEnabled(false);
        this.txtUsuario.setEditable(false);
        this.txtContraseña.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        brnRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnSubir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CLIENTE ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 70, -1, 26));

        jLabel2.setText("DNI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 167, -1, -1));

        jLabel3.setText("DIRECCION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 117, -1, -1));

        jLabel4.setText("DISTRITO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 213, -1, -1));

        jLabel5.setText("CELULAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 265, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 114, 108, -1));
        getContentPane().add(txtDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 177, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 73, 177, -1));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 262, 104, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 161, 177, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 478, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 478, -1, -1));

        brnRegresar.setText("REGRESAR");
        brnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(brnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 478, -1, -1));

        jLabel6.setText("USUARIO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 360, 57, -1));

        jLabel7.setText("CONTRASEÑA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 398, -1, -1));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 395, 140, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 357, 140, -1));

        btnSubir.setText("SUBIR");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRegresarActionPerformed
        // TODO add your handling code here:
        /*FrameGestionClientes frm = new FrameGestionClientes();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);*/
                this.dispose();
      
      
    }//GEN-LAST:event_brnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        Cliente cliente;

        try{

            if(!this.validarFormAgregar()){

            }else{
                
                //Ubigeo ubigeo = (Ubigeo)this.cboDistritos.getSelectedItem();
              
                cliente = new Cliente(this.txtDni.getText(),this.txtNombre.getText(), 
                        this.txtDireccion.getText(),this.txtDistrito.getText(), 
                        this.txtCelular.getText());
                
               
                
                int confirmado = JOptionPane.showConfirmDialog(this,"¿seguro?");
                
                if(JOptionPane.OK_OPTION==confirmado){
                    
                Configuracion.listaClientes.agregar(cliente);
                Configuracion.usuarios.add(new Usuario(this.txtNombre.getText(), 
                        this.txtUsuario.getText(), this.txtContraseña.getText()));
                SerializadoraGen.serializar("UsuariosBD",Configuracion.usuarios);
                SerializadoraGen.serializar("ClientesBD",Configuracion.listaClientes);
                JOptionPane.showMessageDialog(this, "AGREGADO EXITOSAMENTE");
                this.limpiar();
                    
                }
                
           
            }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ERROR");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         try{
            int p =0;
            if(!this.validarFormModificar()){

            }else{
                //Ubigeo ubigeo = (Ubigeo)this.cboDistritos.getSelectedItem();
                p = Configuracion.listaClientes.posicionDeCliente(c);
                c.setNombre(this.txtNombre.getText());
                c.setCelular(this.txtCelular.getText());
                c.setDireccion(this.txtDireccion.getText());
                c.setDNI(this.txtDni.getText());
                c.setDistrito(this.txtDistrito.getText());
                
                Configuracion.listaClientes.modificarPersona(c);
                
                JOptionPane.showMessageDialog(this, "MODIFICADO EXITOSO");

                FrameGestionClientes frm = new FrameGestionClientes();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
                this.dispose();
            }

        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"ERROR: "+e);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File archivo = fc.getSelectedFile();
        if(archivo  != null){
            this.txtDni.setText(archivo.getName());
        }
        
    }//GEN-LAST:event_btnSubirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new FrameCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRegresar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables


    private void limpiar(){
    
   // this.txtAltura.setText("");
    //this.txtDNI.setText("");
    this.txtDireccion.setText("");
    this.txtNombre.setText("");
    this.txtCelular.setText("");
    this.txtDni.setText("");
    this.txtDistrito.setText("");
    this.txtUsuario.setText("");
    this.txtContraseña.setText("");
}
    
    
    
    
    private boolean validarFormAgregar(){
        boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL JUGADOR", "NOMBRE", ERROR_MESSAGE);
        
        }else if(Configuracion.listaClientes.obtenerPersonaPorNombre(this.txtNombre.getText())!=null){
            JOptionPane.showMessageDialog(this, "EL CLIENTE YA EXISTE", "NOMBRE",ERROR_MESSAGE);
            
        }else if(this.txtDireccion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA DIRECCION", "DIRECCION", ERROR_MESSAGE);
        }else if(this.txtDni.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL DNI", "DNI", ERROR_MESSAGE);
        }else if(Configuracion.listaClientes.obtenerPersonaPorDni(txtDni.getText())!=null){
            JOptionPane.showMessageDialog(this, "DNI YA REGISTRADO ", "DNI", ERROR_MESSAGE);
        }
        else if(this.txtDistrito.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL DISTRITO", "DISTRITO", ERROR_MESSAGE);
        }else if(this.txtCelular.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL CELULAR", "CELULAR", ERROR_MESSAGE);
        }else if(Configuracion.usuarios.findUsuario(txtUsuario.getText())){
            JOptionPane.showMessageDialog(this, "USER YA REGISTRADO ", "USER", ERROR_MESSAGE);
        }
        
        else{
            result = true;
        }
        return result;     
    } 


    public void inicializarCampos(){
        

        this.txtDni.setText(c.getDNI());
        this.txtCelular.setText(c.getCelular());
        this.txtDireccion.setText(c.getDireccion());
        this.txtDistrito.setText(c.getDistrito());
        this.txtNombre.setText(c.getNombre());
       
       // this.cboDepartamentos.setSelectedItem(j.getUbigeo());
        
    } 
    
    
    private boolean validarFormModificar(){
         boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL CLIENTE", "NOMBRE", ERROR_MESSAGE);
        }else if(this.txtDireccion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA DIRECCION", "DIRECCION", ERROR_MESSAGE);
        }else if(this.txtDni.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL DNI", "DNI", ERROR_MESSAGE);
        }else if(this.txtDistrito.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL DISTRITO", "DISTRITO", ERROR_MESSAGE);
        }else if(this.txtCelular.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL CELULAR", "CELULAR", ERROR_MESSAGE);
        }else{
            if(this.validarModificacion()){
                
             result = true;   
             
            }
        }
        return result;     
    } 

 
     private boolean validarModificacion(){
         boolean result=true;
         
          if(!this.txtNombre.getText().equals(this.c.getNombre())){
            if(Configuracion.listaClientes.obtenerPersonaPorNombre(this.txtNombre.getText())!=null){
              JOptionPane.showMessageDialog(this, "EL NOMBRE YA EXISTE", "NOMBRE",ERROR_MESSAGE);
              result=false;  
            }
            
          }else if(!this.txtDni.getText().equals(c.getDNI())){
              if(Configuracion.listaClientes.obtenerPersonaPorDni(txtDni.getText())!=null){
                 JOptionPane.showMessageDialog(this, "DNI YA REGISTRADO", "DNI", ERROR_MESSAGE);
                 result=false; 
              }
              
               
          }
         
         return result;
     }
    
    
}
