/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Producto;
import Enumerados.Tipos;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import sistema.Configuracion;
import sistema.SerializadoraGen;

/**
 *
 * @author USUARIO
 */
public class FrameProductos extends javax.swing.JFrame {

    /**
     * Creates new form FrameProductos
     */
    Producto p;
    public FrameProductos() {
        initComponents();
        this.btnModificar.setEnabled(false);
        this.txtID.setText(String.valueOf(Configuracion.IDP));
    }
    
     public FrameProductos(Producto c){
        initComponents();
        this.p=c;
       
        this.inicializarCampos();
        this.btnAgregar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        brnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        cboTipos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VENTANA PRODUCTO");
        setMinimumSize(new java.awt.Dimension(380, 528));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("PRECIO");

        brnRegresar.setText("REGRESAR");
        brnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRegresarActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jLabel4.setText("CATEGORIA");

        jLabel5.setText("STOCK");

        txtID.setEditable(false);

        txtCategoria.setEditable(false);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE");

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        cboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTipos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(131, 131, 131))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(brnRegresar)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(117, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtID))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCategoria)
                    .addComponent(cboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(brnRegresar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRegresarActionPerformed
        // TODO add your handling code here:
        FrameGestionProductos frm = new FrameGestionProductos();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
                this.dispose();
       

    }//GEN-LAST:event_brnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        Producto producto;

        try{

            if(!this.validarFormAgregar()){

            }else{

                //Ubigeo ubigeo = (Ubigeo)this.cboDistritos.getSelectedItem();

                producto = new Producto(this.txtID.getText(),this.txtNombre.getText(),
                    Float.valueOf(this.txtPrecio.getText()),this.txtCategoria.getText(),
                    Integer.parseInt(this.txtStock.getText()));

                int confirmado = JOptionPane.showConfirmDialog(this,"¿seguro?");

                if(JOptionPane.OK_OPTION==confirmado){
                     Configuracion.IDP++; //el idp varia       
                    Configuracion.listaProductos.agregar(producto);
                    SerializadoraGen.serializar("ProductosBD",Configuracion.listaProductos);
                    JOptionPane.showMessageDialog(this, "AGREGADO EXITOSAMENTE");
                    this.limpiar();

                }

            }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ERROR");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
            int po =0;
            if(!this.validarFormModificar()){

            }else{
                //Ubigeo ubigeo = (Ubigeo)this.cboDistritos.getSelectedItem();
                po = Configuracion.listaProductos.posicionDeProducto(p);
                p.setNombre(this.txtNombre.getText());
                p.setStock(Integer.parseInt(this.txtStock.getText()));
                p.setID(this.txtID.getText());
                p.setPrecio(Float.valueOf(this.txtPrecio.getText()));
                p.setCategoria(this.txtCategoria.getText());

                Configuracion.listaProductos.ModificarProducto(p);

                JOptionPane.showMessageDialog(this, "MODIFICADO EXITOSO");

                FrameGestionProductos frm= new FrameGestionProductos();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
                this.dispose();
            }

        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"ERROR: "+e);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void cboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTiposActionPerformed
        // TODO add your handling code here:
        String tipo = (String)this.cboTipos.getSelectedItem();
        this.txtCategoria.setText(tipo);
    }//GEN-LAST:event_cboTiposActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         this.cargarComboBox();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRegresar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables


private boolean validarFormAgregar(){
        boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL PRODUCTO", "NOMBRE", ERROR_MESSAGE);
        
        }else if(Configuracion.listaProductos.obtenerProductoPorNombre(this.txtNombre.getText())!=null){
            JOptionPane.showMessageDialog(this, "EL PRODUCTO YA EXISTE", "NOMBRE",ERROR_MESSAGE);
            
        }else if(this.txtPrecio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL PRECIO", "PRECIO", ERROR_MESSAGE);
        }else if(this.txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL ID", "ID", ERROR_MESSAGE);
        }else if(Configuracion.listaProductos.obtenerProducto(txtID.getText())!=null){
            JOptionPane.showMessageDialog(this, "ID YA REGISTRADO ", "ID", ERROR_MESSAGE);
        }
        else if(this.txtCategoria.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA CATEGORIA", "CATEGORIA", ERROR_MESSAGE);
        }else if(this.txtStock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL STOCK", "STOCK", ERROR_MESSAGE);
        }
        
        else{
            result = true;
        }
        return result;     
    } 

    private void limpiar(){
        this.txtCategoria.setText("");
        this.txtID.setText("");
        this.txtNombre.setText("");
        this.txtPrecio.setText("");
        this.txtStock.setText("");
    }
    
    
      public void inicializarCampos(){
        

        this.txtCategoria.setText(p.getCategoria());
        this.txtID.setText(p.getID());
        this.txtNombre.setText(p.getNombre());
        this.txtPrecio.setText(String.valueOf(p.getPrecio()));
        this.txtStock.setText(String.valueOf(p.getStock()));
      
       // this.cboDepartamentos.setSelectedItem(j.getUbigeo());
        
    } 
      
     private boolean validarFormModificar(){
         boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL CLIENTE", "NOMBRE", ERROR_MESSAGE);
        }else if(this.txtCategoria.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA CATEGORIA", "CATEGORIA", ERROR_MESSAGE);
        }else if(this.txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL ID", "ID", ERROR_MESSAGE);
        }else if(this.txtPrecio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL PRECIO", "PRECIO", ERROR_MESSAGE);
        }else if(this.txtStock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL STOCK", "STOCK", ERROR_MESSAGE);
        }else{
            if(this.validarModificacion()){
                
             result = true;   
             
            }
        }
        return result;     
    } 

 
     private boolean validarModificacion(){
         boolean result=true;
         
          if(!this.txtNombre.getText().equals(this.p.getNombre())){
            if(Configuracion.listaProductos.obtenerProductoPorNombre(this.txtNombre.getText())!=null){
              JOptionPane.showMessageDialog(this, "EL NOMBRE YA EXISTE", "NOMBRE",ERROR_MESSAGE);
              result=false;  
            }
            
          }else if(!this.txtID.getText().equals(p.getID())){
              if(Configuracion.listaProductos.obtenerProducto(txtID.getText())!=null){
                 JOptionPane.showMessageDialog(this, "ID YA REGISTRADO", "DNI", ERROR_MESSAGE);
                 result=false; 
              }
              
               
          }
         
         return result;
     } 
      
       private void cargarComboBox(){
         
         for(int i=0;i<Tipos.values().length;i++){
             
             this.cboTipos.addItem(Tipos.values()[i].name());
         }
         
         
         
         
     }
      
}

